### ISSUE TITLE
Develop Navbar that is common to all webpages, similar to the design below

### ISSUE THREAD

**Issue by Nishkarsh01** [Nishkarsh01/defending-himalayas-website#2]
1) The title for the webpage would be: Defending Himalayas
2)  The logo "NewsGrid" must be replaced with text Defending Himalayas, the color for it should be #1da64a
3) Navbar should contain links, "Home", "About", "Join Us", "Donation", "Blog", "Contact us".
4) The current link should have the background color of #1da64a, and the text color of #fff or white
5) It is not a necessity to include social media icons in the navbar
6) The navbar must stick to the top upon scrolling (use position: sticky, top: 0)

![navbar](https://user-images.githubusercontent.com/60971213/140619131-fbcebc99-b412-4787-9245-f3cc1f067957.jpg)

**Comment by ilyasbabu** [comment]
on it

**Comment by Nishkarsh01** [comment]
Great Job @ilyasbabu
